services:
  - type: web
    name: voice-ai-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    branch: main
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true
